package mms;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class AdminMenuView extends javax.swing.JFrame {

    int id;

    public AdminMenuView(int id) {
        initComponents();
        show_stockTable(0);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.id = id;
        System.out.println("Current ID:" + id);
    }

    public void close() {
        this.setVisible(false);
        this.dispose();
    }

    public void show_stockTable(int s) {

        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        ArrayList<Stock> list = db.stockList(s);
        DefaultTableModel model = (DefaultTableModel) stockTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getMed_name();
            row[2] = list.get(i).getPrice();
            row[3] = list.get(i).getQty();
            row[4] = list.get(i).getManf_name();
            row[5] = list.get(i).getExp_date();

            model.addRow(row);

        }
        for (int i = 0; i < stockTable.getRowCount(); i++) {

            stockTable.setValueAt(list.get(i).getId(), i, 0);
            stockTable.setValueAt(list.get(i).getMed_name(), i, 1);
            stockTable.setValueAt(list.get(i).getPrice(), i, 2);
            stockTable.setValueAt(list.get(i).getQty(), i, 3);
            stockTable.setValueAt(list.get(i).getManf_name(), i, 4);
            stockTable.setValueAt(list.get(i).getExp_date(), i, 5);
            stockTable.setValueAt(false, i, 6);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stockTable = new javax.swing.JTable();
        priceAscRadBtn = new javax.swing.JRadioButton();
        NameAscRadBtn = new javax.swing.JRadioButton();
        NameDesRadBtn = new javax.swing.JRadioButton();
        priceDescRadBtn = new javax.swing.JRadioButton();
        insertBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        odrText = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalAmt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        empBtn = new javax.swing.JButton();
        orderViewBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(96, 6, 19));
        jLabel6.setText("Administrator Menu");

        stockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price per Unit", "Available quantity", "Manufacturer", "Expire Date", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(stockTable);
        if (stockTable.getColumnModel().getColumnCount() > 0) {
            stockTable.getColumnModel().getColumn(0).setResizable(false);
            stockTable.getColumnModel().getColumn(1).setResizable(false);
            stockTable.getColumnModel().getColumn(2).setResizable(false);
            stockTable.getColumnModel().getColumn(3).setResizable(false);
            stockTable.getColumnModel().getColumn(4).setResizable(false);
            stockTable.getColumnModel().getColumn(6).setResizable(false);
        }

        priceAscRadBtn.setText("Price Asc");

        NameAscRadBtn.setText("Name Asc");

        NameDesRadBtn.setText("Name Desc");

        priceDescRadBtn.setText("Price Desc");
        priceDescRadBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                priceDescRadBtnItemStateChanged(evt);
            }
        });

        insertBtn.setText("Insert New Medicine");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sort By:");

        odrText.setColumns(20);
        odrText.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        odrText.setRows(5);
        jScrollPane2.setViewportView(odrText);

        jLabel2.setText("Name");

        jLabel3.setText("Order Quantity");

        jLabel4.setText("Price");

        jLabel5.setText("Total Amount:");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel7.setText("Orders");

        deleteBtn.setText("Delete Selected");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Selected");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel8.setText("Search");

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        empBtn.setText("Employees");
        empBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empBtnActionPerformed(evt);
            }
        });

        orderViewBtn.setText("Orders");
        orderViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderViewBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(empBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(84, 84, 84)
                                    .addComponent(orderViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(NameDesRadBtn)
                                    .addGap(10, 10, 10)
                                    .addComponent(NameAscRadBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(priceDescRadBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(priceAscRadBtn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(49, 49, 49)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addGap(8, 8, 8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(insertBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(updateBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(deleteBtn)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(totalAmt)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NameDesRadBtn)
                                    .addComponent(NameAscRadBtn)
                                    .addComponent(priceDescRadBtn)
                                    .addComponent(priceAscRadBtn)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(orderViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceDescRadBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_priceDescRadBtnItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            show_stockTable(2);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            show_stockTable(0);
        }
    }//GEN-LAST:event_priceDescRadBtnItemStateChanged

    String s = "";
    boolean canConfirm = false;
    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed

        InsertMedView v = new InsertMedView();
        v.setVisible(true);
        this.close();


    }//GEN-LAST:event_insertBtnActionPerformed


    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        Boolean canDelete = false;
        Boolean select_checked = false;
        Vector<Integer> medId = new Vector<>();
        for (int i = 0; i < stockTable.getRowCount(); i++) {
            select_checked = (boolean) stockTable.getValueAt(i, 6);
            //

            if (select_checked == true) {
                medId.add((int) stockTable.getValueAt(i, 0));
                canDelete = true;
            }

        }
        int p = JOptionPane.showConfirmDialog(null, "Are you sure to delete these data?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0 && canDelete == true) {
            deleteMed(medId);
        } else {
            JOptionPane.showMessageDialog(null, "No data to delete");
        }
        show_stockTable(0);

    }//GEN-LAST:event_deleteBtnActionPerformed

    void deleteMed(Vector<Integer> medId) {

        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        Connection connect = db.connect;
        ResultSet rs = null;

        try {

            for (int i = 0; i < medId.size(); i++) {
                String query = "DELETE FROM medicine WHERE med_id =?";
                PreparedStatement pStatement = connect.prepareStatement(query);
                pStatement.setInt(1, medId.get(i));

                pStatement.executeUpdate();
            }
            System.out.println("DELETE Medicine Query Done");

        } catch (Exception e) {
            System.out.println("DELETE MEDECINE Query Failed");
            e.printStackTrace();
        }

    }


    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        Boolean canUpdate = false;
        Boolean select_checked = false;

        for (int i = 0; i < stockTable.getRowCount(); i++) {
            select_checked = (boolean) stockTable.getValueAt(i, 6);
            if (select_checked == true) {
                String medId = stockTable.getValueAt(i, 0).toString();
                String medName = stockTable.getValueAt(i, 1).toString();
                String medPrice = stockTable.getValueAt(i, 2).toString();
                String medQty = stockTable.getValueAt(i, 3).toString();
                String manfName = stockTable.getValueAt(i, 4).toString();
                String expDate = stockTable.getValueAt(i, 5).toString();

                updateMed(medId, medName, medPrice, medQty, manfName, expDate);
            }

        }

        show_stockTable(0);


    }//GEN-LAST:event_updateBtnActionPerformed

    void updateMed(String medId, String medName, String medPrice, String medQty, String manfName, String expDate) {

        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        Connection connect = db.connect;
        try {

            String query1 = "UPDATE medicine SET med_id = ?, name = ?,price = ?,avl_quantity = ?" + "WHERE med_id = ?";
            PreparedStatement pStatement = connect.prepareStatement(query1);
            pStatement.setString(1, medId);
            pStatement.setString(2, medName);
            pStatement.setString(3, medPrice);
            pStatement.setString(4, medQty);
            pStatement.setString(5, medId);

            pStatement.executeUpdate();

            String query2 = "UPDATE stock SET med_id = ?, manf_name = ?,exp_date=?" + "WHERE med_id = ?";
            PreparedStatement p2Statement = connect.prepareStatement(query2);
            p2Statement.setString(1, medId);
            p2Statement.setString(2, manfName);
            p2Statement.setString(3, expDate);
            p2Statement.setString(4, medId);

            p2Statement.executeUpdate();
            System.out.println("Update Query Done");
        } catch (Exception e) {
            System.out.println("Update Query Failed");
            e.printStackTrace();
        }

    }


    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        search(searchField.getText().toString());
    }//GEN-LAST:event_searchFieldKeyReleased

    private void empBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empBtnActionPerformed
        EmployeeListView v=new EmployeeListView(0);
        v.setVisible(true);
        
    }//GEN-LAST:event_empBtnActionPerformed

    private void orderViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderViewBtnActionPerformed
        OrderListView v=new OrderListView(0);
        v.setVisible(true);
        
    }//GEN-LAST:event_orderViewBtnActionPerformed

    public void search(String searchString) {
        DefaultTableModel model = (DefaultTableModel) stockTable.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);
        stockTable.setRowSorter(rowSorter);

        rowSorter.setRowFilter(RowFilter.regexFilter(searchString));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                int c = 0;
                new AdminMenuView(c).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NameAscRadBtn;
    private javax.swing.JRadioButton NameDesRadBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton empBtn;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea odrText;
    private javax.swing.JButton orderViewBtn;
    private javax.swing.JRadioButton priceAscRadBtn;
    private javax.swing.JRadioButton priceDescRadBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JTable stockTable;
    private javax.swing.JTextField totalAmt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
