package mms;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class EmployeeListView extends javax.swing.JFrame {

    int id;

    public EmployeeListView(int id) {
        initComponents();
        show_employeeTable(0);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.id = id;
        //System.out.println("Current ID:" + id);
    }

    public void close() {
        this.setVisible(false);
        this.dispose();
    }

    public void show_employeeTable(int s) {

        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        ArrayList<Employee> emplist = db.empList(s);
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i = 0; i < emplist.size(); i++) {
            row[0] = emplist.get(i).getId();
            row[1] = emplist.get(i).getName();
            row[2] = emplist.get(i).getPhone();
            row[3] = emplist.get(i).getAddress();
            row[4] = emplist.get(i).getUser_name();
            row[5] = emplist.get(i).getPassword();

            model.addRow(row);

        }
        for (int i = 0; i < empTable.getRowCount(); i++) {

            empTable.setValueAt(emplist.get(i).getId(), i, 0);
            empTable.setValueAt(emplist.get(i).getName(), i, 1);
            empTable.setValueAt(emplist.get(i).getPhone(), i, 2);
            empTable.setValueAt(emplist.get(i).getAddress(), i, 3);
            empTable.setValueAt(emplist.get(i).getUser_name(), i, 4);
            empTable.setValueAt(emplist.get(i).getPassword(), i, 5);
            empTable.setValueAt(false, i, 6);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        empTable = new javax.swing.JTable();
        priceAscRadBtn = new javax.swing.JRadioButton();
        NameAscRadBtn = new javax.swing.JRadioButton();
        NameDesRadBtn = new javax.swing.JRadioButton();
        priceDescRadBtn = new javax.swing.JRadioButton();
        insertBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(96, 6, 19));
        jLabel6.setText("Employee Info");

        empTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Phone", "Address", "UserName", "Password", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(empTable);
        if (empTable.getColumnModel().getColumnCount() > 0) {
            empTable.getColumnModel().getColumn(0).setResizable(false);
            empTable.getColumnModel().getColumn(1).setResizable(false);
            empTable.getColumnModel().getColumn(2).setResizable(false);
            empTable.getColumnModel().getColumn(3).setResizable(false);
            empTable.getColumnModel().getColumn(4).setResizable(false);
            empTable.getColumnModel().getColumn(5).setResizable(false);
            empTable.getColumnModel().getColumn(6).setResizable(false);
        }

        priceAscRadBtn.setText("Price Asc");

        NameAscRadBtn.setText("Name Asc");

        NameDesRadBtn.setText("Name Desc");

        priceDescRadBtn.setText("Price Desc");
        priceDescRadBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                priceDescRadBtnItemStateChanged(evt);
            }
        });

        insertBtn.setText("Insert New Employee");
        insertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sort By:");

        deleteBtn.setText("Delete Selected");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Selected");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel8.setText("Search");

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameDesRadBtn)
                                .addGap(10, 10, 10)
                                .addComponent(NameAscRadBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceDescRadBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceAscRadBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(insertBtn)
                        .addGap(34, 34, 34)
                        .addComponent(updateBtn)
                        .addGap(27, 27, 27)
                        .addComponent(deleteBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameDesRadBtn)
                            .addComponent(NameAscRadBtn)
                            .addComponent(priceDescRadBtn)
                            .addComponent(priceAscRadBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(insertBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceDescRadBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_priceDescRadBtnItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            show_employeeTable(2);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            show_employeeTable(0);
        }
    }//GEN-LAST:event_priceDescRadBtnItemStateChanged

    String s = "";
    boolean canConfirm = false;
    private void insertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertBtnActionPerformed

        InsertEmpView v = new InsertEmpView();
        v.setVisible(true);
        this.close();


    }//GEN-LAST:event_insertBtnActionPerformed


    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        Boolean canDelete = false;
        Boolean select_checked = false;
        Vector<Integer> eId = new Vector<>();
        for (int i = 0; i < empTable.getRowCount(); i++) {
            select_checked = (boolean) empTable.getValueAt(i, 6);
            //

            if (select_checked == true) {
                eId.add((int) empTable.getValueAt(i, 0));
                canDelete = true;
            }

        }
        int p = JOptionPane.showConfirmDialog(null, "Are you sure to delete these data?", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0 && canDelete == true) {
            deleteEmp(eId);
        } else {
            JOptionPane.showMessageDialog(null, "No data to delete");
        }
        show_employeeTable(0);

    }//GEN-LAST:event_deleteBtnActionPerformed

    void deleteEmp(Vector<Integer> medId) {

        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        Connection connect = db.connect;
        ResultSet rs = null;

        try {

            for (int i = 0; i < medId.size(); i++) {
                String query = "DELETE FROM employee WHERE e_id =?";
                PreparedStatement pStatement = connect.prepareStatement(query);
                pStatement.setInt(1, medId.get(i));

                pStatement.executeUpdate();
            }
            System.out.println("DELETE Employee Query Done");

        } catch (Exception e) {
            System.out.println("DELETE Employee Query Failed");
            e.printStackTrace();
        }

    }


    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        Boolean canUpdate = false;
        Boolean select_checked = false;

        for (int i = 0; i < empTable.getRowCount(); i++) {
            select_checked = (boolean) empTable.getValueAt(i, 6);
            if (select_checked == true) {
                String eId = empTable.getValueAt(i, 0).toString();
                String name = empTable.getValueAt(i, 1).toString();
                String phone = empTable.getValueAt(i, 2).toString();
                String address = empTable.getValueAt(i, 3).toString();
                String uName = empTable.getValueAt(i, 4).toString();
                String pass = empTable.getValueAt(i, 5).toString();

                updateEmp(eId,  name,  phone, address, uName, pass);
            }

        }

       show_employeeTable(0);


    }//GEN-LAST:event_updateBtnActionPerformed

    void updateEmp(String eId, String name, String phone, String address, String uName, String pass) {

        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        Connection connect = db.connect;
        try {

            String query1 = "UPDATE employee SET e_id = ?, name = ?,phone = ?,address = ?,user_name = ?,password = ?" + "WHERE e_id = ?";
            PreparedStatement pStatement = connect.prepareStatement(query1);
            pStatement.setString(1, eId);
            pStatement.setString(2, name);
            pStatement.setString(3, phone);
            pStatement.setString(4, address);
            pStatement.setString(5, uName);
            pStatement.setString(6, pass);
            pStatement.setString(7, eId);

            pStatement.executeUpdate();
            System.out.println("Update Query Done");
        } catch (Exception e) {
            System.out.println("Update Query Failed");
            e.printStackTrace();
        }

    }


    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        search(searchField.getText().toString());
    }//GEN-LAST:event_searchFieldKeyReleased

    public void search(String searchString) {
        DefaultTableModel model = (DefaultTableModel) empTable.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);
        empTable.setRowSorter(rowSorter);

        rowSorter.setRowFilter(RowFilter.regexFilter(searchString));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                int c = 0;
                new EmployeeListView(c).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NameAscRadBtn;
    private javax.swing.JRadioButton NameDesRadBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTable empTable;
    private javax.swing.JButton insertBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton priceAscRadBtn;
    private javax.swing.JRadioButton priceDescRadBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
