package mms;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class OrderListView extends javax.swing.JFrame {

    int id;

    public OrderListView(int id) {
        initComponents();
        show_orderTable(0);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.id = id;
        //System.out.println("Current ID:" + id);
    }

    public void close() {
        this.setVisible(false);
        this.dispose();
    }

    public void show_orderTable(int s) {

        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        ArrayList<DetailOrder> orderlist = db.orderList(s);
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        model.setRowCount(0);
        Object[] row = new Object[6];
        for (int i = 0; i < orderlist.size(); i++) {
            row[0] = orderlist.get(i).getOrder_no();
            row[1] = orderlist.get(i).getC_id();
            row[2] = orderlist.get(i).getOrder_time();
            row[3] = orderlist.get(i).getOrder_val();
            row[4] = orderlist.get(i).getOrder_prcsd();
            
            model.addRow(row);

        }
        for (int i = 0; i < orderTable.getRowCount(); i++) {

            orderTable.setValueAt(orderlist.get(i).getOrder_no(), i, 0);
            orderTable.setValueAt(orderlist.get(i).getC_id(), i, 1);
            orderTable.setValueAt(orderlist.get(i).getOrder_time(), i, 2);
            orderTable.setValueAt(orderlist.get(i).getOrder_val(), i, 3);
            orderTable.setValueAt(orderlist.get(i).getOrder_prcsd(), i, 4);
            orderTable.setValueAt(false, i, 5);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        priceAscRadBtn = new javax.swing.JRadioButton();
        NameAscRadBtn = new javax.swing.JRadioButton();
        NameDesRadBtn = new javax.swing.JRadioButton();
        priceDescRadBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        detailBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTxt = new javax.swing.JTextArea();
        clrViewBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(96, 6, 19));
        jLabel6.setText("ORDER LIST");

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Customer ID", "Time", "Value(Tk.)", "Processed", "Select"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
            orderTable.getColumnModel().getColumn(4).setResizable(false);
            orderTable.getColumnModel().getColumn(5).setResizable(false);
        }

        priceAscRadBtn.setText("Price Asc");

        NameAscRadBtn.setText("Name Asc");

        NameDesRadBtn.setText("Name Desc");

        priceDescRadBtn.setText("Price Desc");
        priceDescRadBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                priceDescRadBtnItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sort By:");

        detailBtn.setText("Detail of Selected Orders");
        detailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 24)); // NOI18N
        jLabel8.setText("Search");

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        orderTxt.setColumns(20);
        orderTxt.setRows(5);
        jScrollPane2.setViewportView(orderTxt);

        clrViewBtn.setText("Clear View");
        clrViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrViewBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Order No.");

        jLabel3.setText("Medicine Id");

        jLabel4.setText("Medicine Name");

        jLabel5.setText("Quantity");

        jLabel7.setText("Employee");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameDesRadBtn)
                                .addGap(10, 10, 10)
                                .addComponent(NameAscRadBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(priceDescRadBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceAscRadBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(detailBtn)
                                .addGap(47, 47, 47)
                                .addComponent(clrViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel3)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel4)
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(28, 28, 28))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameDesRadBtn)
                            .addComponent(NameAscRadBtn)
                            .addComponent(priceDescRadBtn)
                            .addComponent(priceAscRadBtn)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(detailBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clrViewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void priceDescRadBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_priceDescRadBtnItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            show_orderTable(2);
        } else if (evt.getStateChange() == ItemEvent.DESELECTED) {
            show_orderTable(0);
        }
    }//GEN-LAST:event_priceDescRadBtnItemStateChanged

    String s = "";
   
    
    private void detailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailBtnActionPerformed
        float total = 0;
        orderTxt.setText("");
       
        String s1 = "";

        for (int i = 0; i < orderTable.getRowCount(); i++) {
            Boolean select_checked = (boolean) orderTable.getValueAt(i, 5);
            //int amtval = (int) medTable.getValueAt(i, 5);
            //float priceval = (float) medTable.getValueAt(i, 2);

            String col = orderTable.getValueAt(i, 0).toString();
            //String amt = medTable.getValueAt(i, 5).toString();

            //DISPLAY  
            if (select_checked) {
                //JOptionPane.showMessageDialog(null, col + ",Amount:" + amt);
                //total = total + (priceval * amtval);
                //s1 = col + "\t...     "+ "\n";
                //s = s.concat(s1);
                String detail=showDetail(col);
                
                s=s.concat(detail);
            }


    }                                            

        orderTxt.setText(s);
        s = "";
        

    }//GEN-LAST:event_detailBtnActionPerformed

    String showDetail(String order_no){
        String detail="";
        DatabaseHandler db = new DatabaseHandler();
        db.connectDatabase();
        Connection connect = db.connect;
         ResultSet rs = null;
         System.out.println("COL"+order_no);
         try {
            String query = "SELECT o.order_no,m.med_id,s.name,m.quantity,d.e_id FROM order_info o inner join order_medicine m on o.order_no = m.order_no inner join medicine s on m.med_id = s.med_id inner join deal_emp d on o.order_no=d.order_no WHERE o.order_no=?";
            PreparedStatement pStatement = connect.prepareStatement(query);
            pStatement.setString(1,order_no);

            rs=pStatement.executeQuery();
            
            while (rs.next()) {
                detail=""+rs.getInt("order_no")+"\t..."+rs.getInt("med_id")+"\t..      "+rs.getString("name")+"\t..\t"+rs.getInt("quantity")+"\t.."+rs.getInt("e_id")+"\n";
                            }

            System.out.println("Detail Query Done");
        } catch (Exception e) {
            System.out.println("Query Failed");
            e.printStackTrace();
        }
        
        
        return detail;
    }

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        search(searchField.getText().toString());
    }//GEN-LAST:event_searchFieldKeyReleased

    private void clrViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrViewBtnActionPerformed
        orderTxt.setText("");
        show_orderTable(0);
    }//GEN-LAST:event_clrViewBtnActionPerformed

    public void search(String searchString) {
        DefaultTableModel model = (DefaultTableModel) orderTable.getModel();
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<DefaultTableModel>(model);
        orderTable.setRowSorter(rowSorter);

        rowSorter.setRowFilter(RowFilter.regexFilter(searchString));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                int c = 0;
                new OrderListView(c).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NameAscRadBtn;
    private javax.swing.JRadioButton NameDesRadBtn;
    private javax.swing.JButton clrViewBtn;
    private javax.swing.JButton detailBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextArea orderTxt;
    private javax.swing.JRadioButton priceAscRadBtn;
    private javax.swing.JRadioButton priceDescRadBtn;
    private javax.swing.JTextField searchField;
    // End of variables declaration//GEN-END:variables
}
